### ISSUE TITLE
Error initializing ThisIsPogo: TypeError: window.updateDisplayedLayerGroup is not a function

### ISSUE THREAD

**Issue by elles93** [PoGOHWH/iitc-ce-pogo-s2#12] opened 2023-01-05 09:46 UTC
Hello,
i receive this issue when using the "this is pogo" setting.

Error initializing ThisIsPogo: TypeError: window.updateDisplayedLayerGroup is not a function

It used to work properly, this is the first time in 2 years I get this error. 

I got this error wether I use the old script by Alfonso, or I use your new script. It happens wether I use tampermonkey or I load the plugin directly into IITCE button.

This issues exists both with chrome and with edge browsers

**Comment by 5310** [comment] 2023-01-05 11:24
It's been a _bit_ since I've used or looked at this script to be honest :sweat_smile:  

The last time in #8 I couldn't reproduce the issue at all, but give me some time; but am getting the error now. I'll try to see if I figure it out this time...

**Comment by elles93** [comment] 2023-01-05 11:31
> It's been a _bit_ since I've used or looked at this script to be honest 😅
> 
> The last time in #8 I couldn't reproduce the issue at all, but give me some time; but am getting the error now. I'll try to see if I figure it out this time...

Is there anything I can do to help finding the issue?
At the moment, if I press "this is pogo" it hides the COMM, but it doesn't hide links, fields and it doesn't enhance the interaction radius from 40m to 80m

**Comment by 5310** [comment] 2023-01-05 11:33
It seems that the IITC APIs have changed. Still investigating... 

Will ping you if there's anything to test :+1:

**Comment by elles93** [comment] 2023-01-05 11:42
> It seems that the IITC APIs have changed. Still investigating...
> 
> Will ping you if there's anything to test 👍

Nice, thank you for your time, I'll be here if necessary ;)

**Comment by 5310** [comment] 2023-01-05 11:59
It seems that way back in [December 2021](https://github.com/IITC-CE/ingress-intel-total-conversion/commit/c4b57c4f9693c34ca61ed27c56c33ed8bf902cbc) IITC-CE simply made the layer-group managing API private. 

The odd thing is that it took this long for the script to break. But also, that the docs within the IITC-CE project still mention the `window.updateDisplayedLayerGroup()` function even though they've removed it.

Now trying to see if I can still make the same effect without this funciton.

**Comment by elles93** [comment] 2023-01-05 12:01
> It seems that way back in [December 2021](https://github.com/IITC-CE/ingress-intel-total-conversion/commit/c4b57c4f9693c34ca61ed27c56c33ed8bf902cbc) IITC-CE simply made the layer-group managing API private.
> 
> The odd thing is that it took this long for the script to break. But also, that the docs within the IITC-CE project still mention the `window.updateDisplayedLayerGroup()` function even though they've removed it.
> 
> Now trying to see if I can still make the same effect without this funciton.

Should I try writing to the developers of IITC-CE to see if they can revert this o give some more info?

**Comment by 5310** [comment] 2023-01-05 12:39
Can you remind me something. What are all the changes that used to happen with the This is PoGO checkbox?

1. All portals team colors are reset to orange
2. Links and Fields are hidden
3. And the interaction radius is increased
    - But I forget which radius that is. Is it the yellow-orange circle that shows up when we click on a portal?

Anything else?

**Comment by elles93** [comment] 2023-01-05 12:48
> Can you remind me something. What are all the changes that used to happen with the This is PoGO checkbox?
> 
> 1. All portals team colors are reset to orange
> 2. Links and Fields are hidden
> 3. And the interaction radius is increased
>    
>    * But I forget which radius that is. Is it the yellow-orange circle that shows up when we click on a portal?
> 
> Anything else?

Yes, it's the orange circle. It's 40meters for ingress and 80meters for PoGo.

Moreover, it hids the ingress comm window and remove portals/mod infos under the portal photo. These two functions are preserved and working despite the error.

**Comment by 5310** [comment] 2023-01-05 12:55
So I've updated the script and stopped the error (simply by commenting it out). And so far it does hide the stuff it's supposed to hide, the colors, the fields, the comm window, etc. But it doesn't change the radius because the `window.plugin` list too is no longer accessible :no_mouth:

**Comment by elles93** [comment] 2023-01-05 13:01
> So I've updated the script and stopped the error (simply by commenting it out). And so far it does hide the stuff it's supposed to hide, the colors, the fields, the comm window, etc. But it doesn't change the radius because the `window.plugin` list too is no longer accessible 😶

Quite the irony: the only funcion I needed was the proper drawing of the 80meters radius ahahahah xD
Would it be possible to have a function that draws a 80 meters radius around the selected portal? It could be even another radius in addition to the pre-existent 40meter radius.

**Comment by 5310** [comment] 2023-01-05 13:06
I noticed that wrong. The plugin is only used on mobile (and presumably works there). On the desktop/browser the `window.HACK_RANGE` is changed directly from 40 to 80. 

And it still works...if you refresh the page.

Give it a try. Turn on This is PoGO and refresh the page, the yellow-orange radius will increase. (Which it always was for me so I didn't realize it was 80m). 

Now, as for why it doesn't automatically switch the radius on toggle. It's because another regression that happened with IITC and I couldn't find a way to force re-rendering the map so that the circle radius changes.

**Comment by elles93** [comment] 2023-01-05 13:10
Ok, installed the update and this works wonder.

The radius updates as soon as you click on another portal (as before), no need to refresh the page.

Thank you for the super fast reply! :)

**Comment by 5310** [comment] 2023-01-05 13:12
Ah, that makes sense: It's redrawing the circle if we switch portals. No idea why it doesn't do that automatically though. It's not like there was any other function that needed to be called to do that before.

If I find one such function I'll add it in. For now, marking this as resolved. 

Have a good ~~day~~ year :D

**Closed as completed by 5310** 2023-01-05 13:12 UTC
